---

- hosts: web_servers
  become: true
  tasks:


  - name: install apache and php for Ubuntu servers
    tags: ubuntu-apache
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"


  - name: start apache2
    tags: resume-apache
    service:
      name: apache2
      state: started
    when: ansible_distribution == "Ubuntu"


  - name: copy default html file for site
    tags: site
    copy:
      src: default_site.html
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

- hosts: workstations
  become: true
  tasks:

  - name: install unzip
    package:
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
